# Generated by Django 3.2.8 on 2021-10-14 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hello',
            name='title',
        ),
    ]
