# Generated by Django 3.2.8 on 2021-10-14 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_hello_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='titile',
            new_name='title',
        ),
    ]
